# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # 定时任务，在每天的22点 6点执行
    - cron:  0 22,6 * * *
      # 定时器更改时间
      # https://tool.lu/crontab/
      # https://datetime360.com/cn/utc-cst-china-time/ #UTC时间 国际协调时间+8=北京时间
      # https://docs.github.com/cn/actions/using-workflows/workflow-syntax-for-github-actions#onschedule 官方参考

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run mainCode
        run: python main.py

      - name: commit
        run: |
          git config --global user.email bgmRobot@github.com
          git config --global user.name githubAction
          git add .
          git commit -m "update" -a

      - name: Push changes
        uses: ad-m/github-push-action@master

env:
  #设置secrets的环境变量
  USERID: ${{ secrets.USERID }}
